name: Terraform and kubernetes on GCP

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform on GCP
    runs-on: [self-hosted, gcp-runner]


    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (required for Terraform Action)
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3 

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'kubectl,gke-gcloud-auth-plugin'

      - name: Terraform Init
        run: terraform init
        working-directory: gcp-terraform

      - name: Terraform Plan
        run: terraform plan 
        working-directory: gcp-terraform  
