name: Terraform and kubernetes on GCP

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: Terraform on GCP
    runs-on: [self-hosted, gcp-runner]


    env:
      GOOGLE_CREDENTIALS: ${{ secrets.GCP_CREDENTIALS }}
      PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js (required for Terraform Action)
        run: |
          curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
          sudo apt-get install -y nodejs

      - name: Install unzip
        run: sudo apt-get update && sudo apt-get install -y unzip


      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3 

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: Set up gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          install_components: 'kubectl,gke-gcloud-auth-plugin'

      - name: Terraform Init
        run: terraform init
        working-directory: gcp-terraform

      - name: Terraform Plan
        run: terraform plan 
        working-directory: gcp-terraform  

      - name: Get GKE credentials
        run: |
          gcloud container clusters get-credentials elk-cluster --region asia-southeast1 --project $PROJECT_ID

      - name: Configure Docker for Artifact Registry
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Install Docker
        run: |
          sudo apt update
          sudo apt install docker.io -y
          sudo systemctl enable docker --now
          docker --version
          sudo usermod -aG docker $USER
          getent group docker
          newgrp docker
          sudo service docker restart 
          docker ps

      - name: Build & Push Docker image
        run: |
          COMMIT_SHA=${{ github.sha }}
          docker build -t us-central1-docker.pkg.dev/$PROJECT_ID/roshani-test/demo-app2:$COMMIT_SHA ./k8s
          docker push us-central1-docker.pkg.dev/$PROJECT_ID/roshani-test/demo-app2:$COMMIT_SHA

      - name: Update deployment image with commit SHA
        run: |
         sed -i "s|COMMIT_SHA|$GITHUB_SHA|g" ./k8s/deployment.yaml

      - name: Deploy to GKE
        run: |
          kubectl apply -f ./k8s/deployment.yaml --validate=false
